const images = {
    logo_utotech: require("styles/images/home/logo_utotech.svg"),
    logo_DXP: require("styles/images/home/logo_DXP.svg"),
    logo_jgooooo: require("styles/images/home/logo_jgooooo.svg"),
    logo_utoAcademy: require("styles/images/home/logo_utoAcademy.svg"),
    logo_utoEcoLodge: require("styles/images/home/logo_utoEcoLodge.svg"),
    logo_utoEcoTravel: require("styles/images/home/logo_utoEcoTravel.svg"),
    icon_delete: require("styles/images/home/icon_delete.svg"),
    ip12_jgooooo: require("styles/images/home/ip12_jgooooo.png"),
    headquarters_uto: require("styles/images/home/headquarters_uto.png"),
    aurora_utopia: require("styles/images/home/aurora_utopia.png"),
    travel_uto: require("styles/images/home/travel_uto.png"),
    academy_uto: require("styles/images/home/academy_uto.png"),
    DXP: require("styles/images/home/DXP.png"),
    icon_facebook: require("styles/images/home/icon_facebook.svg"),
    icon_tiktok: require("styles/images/home/icon_tiktok.svg"),
    icon_ytb: require("styles/images/home/icon_ytb.svg"),
    bg_DXP: require("styles/images/home/bg_DXP.png"),
    DXP_banner: require("styles/images/home/DXP_banner.png"),
    DXP_onWindow: require("styles/images/home/DXP_onWindow.png"),
    DXP_paint: require("styles/images/home/DXP_paint.png"),
    arrow_right: require("styles/images/home/arrow_right.svg"),
    icon_arrowLeft: require("styles/images/home/icon_arrowLeft.svg"),
    icon_arrowRight: require("styles/images/home/icon_arrowRight.svg"),
    img_value1: require("styles/images/home/img_value1.png"),
    img_value2: require("styles/images/home/img_value2.png"),
    img_value3: require("styles/images/home/img_value3.png"),
    img_value4: require("styles/images/home/img_value4.png"),
    img_value5: require("styles/images/home/img_value5.png"),
    img_value6: require("styles/images/home/img_value6.png"),
    bg_DXP_mobile: require("styles/images/home/bg_DXP_mobile.png"),
    DXP_mobile: require("styles/images/home/DXP_mobile.png"),
    icon_goToTop: require("styles/images/home/icon_goToTop.svg"),

}
export default images 