const REVIEW_STATUS = {
  SHOW: "SHOW",
  HIDE: "HIDE",
};
const SOURCETYPE = {
  REVIEW: "REVIEW",
  REVIEW_OWNER_AVATAR: "REVIEW_OWNER_AVATAR",
};
const REVIEW_TYPES = {
  NEW: "NORMAL",
  HIGHLIGHT: "MAIN",
};
const REVIEW_COURSE = "REVIEW_COURSE";
const REVIEW_ABOUT_ME = "REVIEW_ABOUT_ME";

export { REVIEW_STATUS, SOURCETYPE, REVIEW_TYPES, REVIEW_COURSE, REVIEW_ABOUT_ME };
